### ISSUE TITLE
Is this still under development? Is this correct repo?

### ISSUE THREAD

**Issue by jrmiller82** [jbmcgill/fxoanda#1]
Hi! I stumbled across this library as I really don't want to use python for an Oanda V20 client. Is it still under development? Or is it low-level but feature complete? Anything missing from it? Did you switch to a different library? 

Thanks in advance and thanks for writing this.

**Comment by jbmcgill** [comment]
Sorry, I missed this. Yes, it's complete in the sense that it's generated from the OANDA v2 spec however I only use some of the functionality for downloading instrument and order data and have not tried the trading APIs. It also does not currently implement the OANDA WebSocket protocol.
