### ISSUE TITLE
Update reqwest::client::Client to current reqwest structs

### ISSUE THREAD

**Issue by jrmiller82** [jbmcgill/fxoanda#2]
```
reqwest: reqwest::Client::new(),
   |     expected struct `reqwest::client::Client`, found struct reqwest::async_impl::client::Client`
```

**Comment by jbmcgill** [comment]
This lib only supports synchronous/blocking clients. It does not accept a reqwest async client. The new reqwest version changed the default new API to return an async client. You could either use an older reqwest (0.9.5 is what I used) or you could try using a new reqwest version with reqwest::blocking::Client. Caveat that I haven't tested it with a newer reqwest version.
